### PR TITLE
Fix removeChild from body.document

### LINKED ISSUE #20: Put the script at the end of body
I see in code
`fjs = d.getElementsByTagName(s)[0]`;
`fjs.parentNode.insertBefore(js, fjs);`
That means we add FB script before the first script tag. However in some case the first script will be placed in **head** tag and we face this error when we try to remove the script and reload it again
error

Why don't we put FB script at the end of body. Ex: `d.body.append(js);`

Could you please to clarify it a bit. Thanks!

### PR DESCRIPTION
**Pull request by xxhomey19**
fix #20

### CODE REVIEW

File: src/MessengerCustomerChat.js [hunk 1]
```diff
@@ -95,12 +95,12 @@ export default class MessengerCustomerChat extends Component {
 
   removeFacebookSDK() {
     const fbjssdk = document.getElementById('facebook-jssdk');
-    if (fbjssdk) {
-      document.body.removeChild(fbjssdk);
+    if (fbjssdk.parentNode) {
```
Comment (hoantran-it) [inline src/MessengerCustomerChat.js]: In some case, fbjssdk can be null at the first load, I suggest to check null for fbjssdk before getting parentNode

File: src/MessengerCustomerChat.js [hunk 2]
```diff
@@ -95,12 +95,12 @@ export default class MessengerCustomerChat extends Component {
...
+      fbjssdk.parentNode.removeChild(fbjssdk);
     }
     const fbroot = document.getElementById('fb-root');
-    if (fbroot) {
-      document.body.removeChild(fbroot);
+    if (fbroot.parentNode) {
```
Comment (hoantran-it) [inline src/MessengerCustomerChat.js]: In some case, fbroot can be null at the first load, I suggest to check null for fbroot before getting parentNode

File: src/MessengerCustomerChat.js (hunk 1 above)
Comment (xxhomey19) [reply src/MessengerCustomerChat.js]: Hey @HLcreativelab ,
Thanks for your comment. I also got this issue, and it will be fix [here](https://github.com/Yoctol/react-messenger-customer-chat/pull/23/files#diff-1e268a73a1c27b1a4e5bc26650aaca16R7). It will be merged soon.

Comment (hoantran-it) [reply src/MessengerCustomerChat.js]: Great! I'm waiting for it. Thanks!

Comment (xxhomey19) [reply src/MessengerCustomerChat.js]: Hi, I turned it to PR #24

Comment (hoantran-it) [reply src/MessengerCustomerChat.js]: @xxhomey19 @chentsulin Great! Hope it will be available soon in 0.6.2 version. Many thanks 💯
